### ISSUE TITLE
Error - Cannot run this plugin from Windows

### ISSUE THREAD

**Issue by D5KDeutsche** [OctoPrint/OctoPrint-MalyanConnectionFix#10]
I've installed Octoprint on a Windows 10 laptop and have installed a few other plugins fine. All things work well with my Ender 3, but I'm trying to install this plugin for my Monoprice Select Mini, but get the error that it can't install from Windows.

**Comment by foosel** [comment]
As stated in the README, and also set in the compatibility flags:

> Note that due to the nature of this sequence this fix can't work for OctoPrint installations on Windows and is therefore not supported for that OS.
