### ISSUE TITLE
MalyanConnectionFix fails with Could not import OctoPrint's setuptools...

### ISSUE THREAD

**Issue by Zenmaster43** [OctoPrint/OctoPrint-MalyanConnectionFix#11]
Printer: MonoPrice Mini Delta IIIP
Server: Raspberry Pi 4B 2GB RAM
Camera: Arducam IM708 (module 3)
OS: Raspberry Pi OS 11 (Bullseye)
OctoPrint: 1.10.2
OctoPi: 1.0.0
Python: 3.9.2

I'm not getting any success trying to connect to the printer from OctoPrint. II tried all options on OctoPrint to connect to the printer by serial (USB) connection, but they all failed.
When I click on the Connect button, the "Disconnect" button is shown, but the "State" remains as "Opening serial connection" and never times out.

I tried to install MalyanConnectionFix, but that fails:

$ sudo pip install https://github.com/OctoPrint/OctoPrint-MalyanConnectionFix/archive/master.zip
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://github.com/OctoPrint/OctoPrint-MalyanConnectionFix/archive/master.zip
  Using cached https://github.com/OctoPrint/OctoPrint-MalyanConnectionFix/archive/master.zip
    ERROR: Command errored out with exit status 255:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-6sajfc8a/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-6sajfc8a/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-5zsjyw9c
         cwd: /tmp/pip-req-build-6sajfc8a/
    Complete output (1 lines):
    Could not import OctoPrint's setuptools, are you sure you are running that under the same python installation that OctoPrint is installed under?
    ----------------------------------------
WARNING: Discarding https://github.com/OctoPrint/OctoPrint-MalyanConnectionFix/archive/master.zip. Command errored out with exit status 255: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 255: python setup.py egg_info Check the logs for full command output.

How can I tell if the python version is correct for the installed OctoPrint version?

Questions:

1) Is this the correct tool to get the serial connection from OctoPrint to my Raspberry Pi?
2) Am I invoking the install correctly?
3) Are the versions I mentioned above compatible with each other?
4) Are the versions I mentioned above compatible with MalyanConnectionFix?
5) If not, is there a version available that is compatible?
6) If none, how can I troubleshoot the serial connection?

Thanks in advance for any assistance you can provide.

**Comment by foosel** [comment]
> 1. Is this the correct tool to get the serial connection from OctoPrint to my Raspberry Pi?

Hopefully, but no guarantees. The workaround implemented by this plugin was discovered by sheer coincidence and it's unclear WHAT exactly is broken in that printer that even requires this to work, so YMMV.

---

> 2. Am I invoking the install correctly?

No. You don't need `sudo`, and you need to invoke the `pip` from your OctoPrint's virtual environment. As you said you use OctoPi, this should work:

```
~/oprint/bin/pip install https://github.com/OctoPrint/OctoPrint-MalyanConnectionFix/archive/master.zip
```

Alternatively, just use OctoPrint's built in plugin repository browser:

![Screenshot from 2024-08-28 09-11-20](https://github.com/user-attachments/assets/a6187f58-0ac0-4ebe-9d82-cb21e9986e1f)
![Screenshot from 2024-08-28 09-11-35](https://github.com/user-attachments/assets/353f308e-a811-4281-8891-0f9d4ac8c98b)

---

> 3. Are the versions I mentioned above compatible with each other?
> 4. Are the versions I mentioned above compatible with MalyanConnectionFix?

I'm unsure about your specific printer model with regards to the plugin, I've so far not seen this specific designation and alas, Monoprice/Malyan don't tell me when they change something.

---

> 5. If none, how can I troubleshoot the serial connection?

Enable serial.log:

![image](https://github.com/user-attachments/assets/d61bfb22-2db5-4ef5-a09b-e7bb5b87a880)

Attempt to connect to your printer. *Then* create a system info bundle:

![image](https://github.com/user-attachments/assets/585b4a7f-6cb2-42f9-9a40-8160b9654065)

![image](https://github.com/user-attachments/assets/cf747d13-9daf-4899-a850-370dc42f17d3)

Open a "Get Help" thread on the [Community Forums](https://community.octoprint.org).
