### ISSUE TITLE
Virtual printer

### ISSUE THREAD

**Issue by realjax** [OctoPrint/OctoPrint-MalyanConnectionFix#2]
Using a virtual printer (http://docs.octoprint.org/en/devel/development/virtual_printer.html) fails when the plugin is enabled.

**Comment by danrohtbart** [comment]
I'm seeing that behavior too. As a workaround, I disable the Malyan plugin before trying to connect to the Virtual Printer.

**Comment by danrohtbart** [comment]
Starting to look into it...not confident I can fix it myself.

**Comment by foosel** [comment]
Has been fixed by the above PR and 0.1.1 was just released containing this fix. Thanks @danrohtbart!
