### ISSUE TITLE
Needs updating for 1.4.0

### ISSUE THREAD

**Issue by PlasmaSoftUK** [OctoPrint/OctoPrint-MalyanConnectionFix#5]
My printer requires this and after installing the latest 1.4.0rc3 it no longer appears in the plugins list, simply adding the compatibility line fixes this and I am able to connect to my printer again. This needs updating and adding to the default repository.

Plasma

**Comment by foosel** [comment]
I take it you are running under Py3 then? Because otherwise this should not need a compat line O_O

**Comment by PlasmaSoftUK** [comment]
Yes that's correct, I'm switching from a Pi3 to a Pi 4 and figured I would have the latest and greatest. With Python 2 going EOL in Jan it seemed like the right time to take the jump.  But I noticed a lot of the plugins are not listed because they are missing this line, even if they do work perfectly well. Themeify is another that even has Python 3 compatibility but doesn't have the Compat line so isn't shown.  :(

**Comment by foosel** [comment]
Compat flag set, 0.1.2 released, repo listing adjusted.

**Comment by foosel** [comment]
> But I noticed a lot of the plugins are not listed because they are missing this line, even if they do work perfectly well.

It would probably help the authors in question if you open tickets like this one in their repos and point them to [this forum post](https://community.octoprint.org/t/towards-python-3-and-octoprint-1-4-0/12382?u=foosel), or better yet a PR.

That being said, while Py2 will be EOL come January 1st that doesn't mean it'll spontanously combust and OctoPrint will have to support it for at least another year to give plugin authors and users time to migrate 🤷‍♀️
