### ISSUE TITLE
Update to 0.1.2 through octopy update seems not to work

### ISSUE THREAD

**Issue by bagong** [OctoPrint/OctoPrint-MalyanConnectionFix#6]
Hi,

I currently get an "update available" message for this plugin (octopi 0.1.3 running on rpi 3, buster, running plugin v. 0.1.1), but when I trigger the install, version 0.1.1 is reinstalled. Therefore I keep getting the update message after each server relaunch...

Thanks for your consideration
.b.

**Comment by foosel** [comment]
Ah darn, I forgot to update the version number. Thanks for the heads-up. Time for a vacation.

**Comment by bagong** [comment]
Thanks for the plugin!

**Comment by foosel** [comment]
0.1.3 is published and should hopefully also report correctly

**Comment by bagong** [comment]
Can't verify that update works now, sorry, but I can confirm that 0.1.3 does install nicely, as I went through uninstall/install around 2 hours ago and got 0.1.3. Best .b.
